spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartroute_qa
    username: postgres
    password: zakaria
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
